package amtt.epam.com.amtt.ticket;

/**
 * Created by Iryna_Monchanka on 5/13/2015.
 */
public enum JiraContentConst {

    PRIORITIES_NAMES,
    PROJECTS_NAMES,
    PROJECT_KEY_BY_NAME,
    ISSUE_TYPES_NAMES,
    VERSIONS_NAMES,
    CREATE_ISSUE,
    USERS_ASSIGNABLE_NAMES,
    META_RESPONSE,
    VERSIONS_RESPONSE,
    CREATE_ISSUE_RESPONSE,
    USERS_ASSIGNABLE_RESPONSE,
    PRIORITIES_RESPONSE
}
