package amtt.epam.com.amtt.api;

/**
 @author Iryna Monchanka
 @version on 5/13/2015
 */

public enum ContentConst {
    PROJECTS_RESPONSE,
    VERSIONS_RESPONSE,
    COMPONENTS_RESPONSE,
    CREATE_ISSUE_RESPONSE,
    USERS_ASSIGNABLE_RESPONSE,
    PRIORITIES_RESPONSE,
    ISSUE_TYPES_RESPONSE,
    DESCRIPTION_RESPONSE,
    ATTACHMENT_RESPONSE,
    SEND_ATTACHMENT,
    SPREADSHEET_RESPONSE,
    WORKSHEET_RESPONSE
}
