package amtt.epam.com.amtt.database;

/**
 * Created by Artsiom_Kaliaha on 19.03.2015.
 */
public interface ActivityInfoConstants {

    String NOT_AVAILABLE = "N/A";
    String NOT_SUPPORTED = "not supported by the API";

    String CONFIG_FONT_SCALE = "CONFIG_FONT_SCALE";
    String CONFIG_MCC = "CONFIG_MCC";
    String CONFIG_MNC = "CONFIG_MNC";
    String CONFIG_LOCALE = "CONFIG_LOCALE";
    String CONFIG_TOUCHSCREEN = "CONFIG_TOUCHSCREEN";
    String CONFIG_KEYBOARD = "CONFIG_KEYBOARD";
    String CONFIG_NAVIGATION = "CONFIG_NAVIGATION";
    String CONFIG_ORIENTATION = "CONFIG_ORIENTATION";
    String CONFIG_SCREEN_LAYOUT = "CONFIG_SCREEN_LAYOUT";
    String CONFIG_LAYOUT_DIRECTION = "CONFIG_LAYOUT_DIRECTION";

    String FLAG_MULTIPROCESS = "FLAG_MULTIPROCESS";
    String FLAG_FINISH_ON_TASK_LAUNCH = "FLAG_FINISH_ON_TASK_LAUNCH";
    String FLAG_CLEAR_TASK_ON_LAUNCH = "FLAG_CLEAR_TASK_ON_LAUNCH";
    String FLAG_ALWAYS_RETAIN_TASK_STATE = "FLAG_ALWAYS_RETAIN_TASK_STATE";
    String FLAG_STATE_NOT_NEEDED = "FLAG_STATE_NOT_NEEDED";
    String FLAG_EXCLUDE_FROM_RECENTS = "FLAG_EXCLUDE_FROM_RECENTS";
    String FLAG_ALLOW_TASK_REPARENTING = "FLAG_ALLOW_TASK_REPARENTING";
    String FLAG_NO_HISTORY = "FLAG_NO_HISTORY";
    String FLAG_FINISH_ON_CLOSE_SYSTEM_DIALOGS = "FLAG_FINISH_ON_CLOSE_SYSTEM_DIALOGS";
    String FLAG_HARDWARE_ACCELERATED = "FLAG_HARDWARE_ACCELERATED";
    String FLAG_SINGLE_USER = "FLAG_SINGLE_USER";

    String LAUNCH_MULTIPLE = "LAUNCH_MULTIPLE";
    String LAUNCH_SINGLE_TOP = "LAUNCH_SINGLE_TOP";
    String LAUNCH_SINGLE_TASK = "LAUNCH_SINGLE_TASK";
    String LAUNCH_SINGLE_INSTANCE = "LAUNCH_SINGLE_INSTANCE";

    String PERSIST_ROOT_ONLY = "persistRootOnly";
    String PERSIST_NEVER = "persistNever";
    String PERSIST_ACROSS_REBOOTS = "persistAcrossReboots";

    String SCREEN_ORIENTATION_UNSPECIFIED = "SCREEN_ORIENTATION_UNSPECIFIED";
    String SCREEN_ORIENTATION_LANDSCAPE = "SCREEN_ORIENTATION_LANDSCAPE";
    String SCREEN_ORIENTATION_PORTRAIT = "SCREEN_ORIENTATION_PORTRAIT";
    String SCREEN_ORIENTATION_USER = "SCREEN_ORIENTATION_USER";
    String SCREEN_ORIENTATION_BEHIND = "SCREEN_ORIENTATION_BEHIND";
    String SCREEN_ORIENTATION_SENSOR = "SCREEN_ORIENTATION_SENSOR";
    String SCREEN_ORIENTATION_NOSENSOR = "SCREEN_ORIENTATION_NOSENSOR";
    String SCREEN_ORIENTATION_SENSOR_LANDSCAPE = "SCREEN_ORIENTATION_SENSOR_LANDSCAPE";
    String SCREEN_ORIENTATION_SENSOR_PORTRAIT = "SCREEN_ORIENTATION_SENSOR_PORTRAIT";
    String SCREEN_ORIENTATION_REVERSE_LANDSCAPE = "SCREEN_ORIENTATION_REVERSE_LANDSCAPE";
    String SCREEN_ORIENTATION_REVERSE_PORTRAIT = "SCREEN_ORIENTATION_REVERSE_PORTRAIT";
    String SCREEN_ORIENTATION_FULL_SENSOR = "SCREEN_ORIENTATION_FULL_SENSOR";
    String SCREEN_ORIENTATION_USER_LANDSCAPE = "SCREEN_ORIENTATION_USER_LANDSCAPE";
    String SCREEN_ORIENTATION_USER_PORTRAIT = "SCREEN_ORIENTATION_USER_PORTRAIT";
    String SCREEN_ORIENTATION_FULL_USER = "SCREEN_ORIENTATION_FULL_USER";
    String SCREEN_ORIENTATION_LOCKED = "SCREEN_ORIENTATION_LOCKED";

    String SOFT_INPUT_STATE_UNSPECIFIED = "SOFT_INPUT_STATE_UNSPECIFIED";
    String SOFT_INPUT_STATE_UNCHANGED = "SOFT_INPUT_STATE_UNCHANGED";
    String SOFT_INPUT_STATE_HIDDEN = "SOFT_INPUT_STATE_HIDDEN";
    String SOFT_INPUT_STATE_ALWAYS_VISIBLE = "SOFT_INPUT_STATE_ALWAYS_VISIBLE";
    String SOFT_INPUT_STATE_VISIBLE = "SOFT_INPUT_STATE_VISIBLE";
    String SOFT_INPUT_ADJUST_UNSPECIFIED = "SOFT_INPUT_ADJUST_UNSPECIFIED";
    String SOFT_INPUT_ADJUST_RESIZE = "SOFT_INPUT_ADJUST_RESIZE";
    String SOFT_INPUT_ADJUST_PAN = "SOFT_INPUT_ADJUST_PAN";

    String UI_OPTIONS_NONE = "UI_OPTIONS_NONE";
    String UI_OPTIONS_SPLIT_ACTIONBAR_WHEN_NARROW = "UI_OPTIONS_SPLIT_ACTIONBAR_WHEN_NARROW";

}
